[package]
name = "tun_nat"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
libc = "0.2.62"
sysconfig = { path = "../sysconfig" }
lazy_static = "1.4.0"
parking_lot = "0.9.0"
bitvec = "0.17.3"
etherparse = "0.9"
smoltcp = "0.6"
