[package]
name = "tun_nat"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.62"
sysconfig = { path = "../sysconfig" }
parking_lot = "0.10"
bitvec = "0.17"
smoltcp = "0.6"
