if: tag IS blank
language: rust
sudo: false
rust:
  - stable
cache: cargo
env:
  BIN_NAME: seeker
matrix:
  include:
    - name: macOS Build
      os: osx
#    - name: Linux Build
#      os: linux
install:
  - ci/travis-libsodium.sh
  - rustup component add rustfmt clippy
script:
  - mkdir -p artifacts
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test --verbose --all
#  - cargo build --release
#  - cp target/release/$BIN_NAME artifacts/$BIN_NAME-$TRAVIS_OS_NAME
before_deploy:
  - export TRAVIS_TAG="preview"
deploy:
  provider: releases
  api_key:
    secure: m2djaZaUqAwPLhVe1ZyLUDy8pj+mo+YSGqFpDGok1gAXoUoH33L1fp67ngbO27BEObKOmuY/CvbgFjc9qItxPSZY4mFev7l2eeRUacJ3RIZEaOIK+C/iN2U7e7EA1PLuRet+DM9Szbi2cIeYuLbJsbDatsGATwbovbUobgDjEiH24md+/ysZHhlAO2QDhaVxFUBv2xzEpHm0h+V9StE6aqx1PwAw07/10Ye9Eo1s4st79V0/IyYU4zE+I3ZGL4mhw5Nf1MIfwurzfToRH8KLe68HFxy8nhIQYTbMXzEa7IQAxKad7WPkLvdFrvEBEFupS4ewmunoamqSIDPPQMDrpzXDIrRtvxms7UtVxXgONOxYLuA+1CLpiew45Tz5pAlrILUtV5bCEtO5Yz8RDtKJqn/ZzgydqX96tl2TYDOJkgSF3kfwF8M6ZC3XfzyEYYuH0FUma8r4sM0Fb0CiUumykZDi/vvDbabs00BnA0XTskkLMsD3eKzgiRS/EEmTO8Q+jH+EDMVu25sNZWXDQNXCiQBkeG/6wl7NT80pCy8P07XVSqT0IkT55/NX2e8DzoGoqT3BdTArcjf/3wDVL3/qnKVAvE+Mv/HHo+DflxiL1tyHZr0E+9jmsKCWDc1QuDJndi7Jw4ZzXeXabu7CXehD3jt8LbhwVv4DXD8eIN3zcE0=
  skip_cleanup: true
  draft: true
  overwrite: true
  file_glob: true
  file: artifacts/$BIN_NAME-*
  on:
    branch: master
