if: tag IS blank
language: rust
sudo: false
rust:
  - stable
cache:
  cargo: true
env:
  - BIN_NAME=seeker
  - SODIUM_BUILD_STATIC=yes
  - SODIUM_STATIC=yes
os: osx
install:
  - rustup component add rustfmt clippy
script:
  - mkdir -p artifacts
  - cargo fmt --all -- --check
  - cargo clippy
  - cargo test --verbose --all
  - cargo build --release
  - cp target/release/$BIN_NAME artifacts/$BIN_NAME-$TRAVIS_OS_NAME
before_deploy:
  - export TRAVIS_TAG="preview"
deploy:
  provider: releases
  api_key: $TOKEN
  skip_cleanup: true
  draft: true
  overwrite: true
  file_glob: true
  file: artifacts/$BIN_NAME-*
  on:
    branch: master
