[package]
name = "seeker"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.59"
bytes = "0.4.12"
byteorder = "1.3.2"
byte_string = "1.0.0"
tokio = "0.1.22"
tokio-signal = "0.2.7"
futures = "0.1.28"
trust-dns = "0.16.1"
trust-dns-resolver = "0.11.1"
trust-dns-server = "0.16.1"
mio = "0.6.19"
managed = "0.7.1"
shadowsocks-rust = {version = "1.7.0", features = ["sodium"], default-features = false}
sled = "0.24.1"
serde = { version = "1.0.99", features = ["derive"] }
serde_yaml = "0.8.9"
tracing = "0.1"
tracing-futures = "0.0.1-alpha.1"
tracing-fmt = "0.0.1-alpha.3"
failure = "0.1.5"

[target.'cfg(macos)'.dependencies]
libproc = { git = "https://github.com/gfreezy/libproc-rs", rev = "bffc2c4", optional = true }

[dependencies.smoltcp]
git = "https://github.com/gfreezy/smoltcp"
rev = "d64d6b9"
default-features = false
features = [
	"std", "log",
	"proto-ipv4",
	"socket-udp",
	"socket-tcp",
	"phy-raw_socket",
]

[dependencies.clap]
version = "2"
