[package]
name = "seeker"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.59"
#runtime = "0.3.0-alpha.6"
#futures-preview = {version = "0.3.0-alpha.17", features = ["compat", "io-compat"]}
#futures01 = { package = "futures", version = "0.1", optional = true }
bytes = "0.4.12"
byteorder = "1.3.2"
byte_string = "1.0.0"
tokio = "0.1.22"
trust-dns-resolver = {version = "0.11.1"}
mio = "0.6.19"
log = "0.4.7"
managed = "0.7.1"
pretty_env_logger = "0.3.0"
better-panic = "0.1.2"
pico-args = "0.2.0"
shadowsocks-rust = {version = "1.7.0", features = ["sodium"], default-features = false}

[dependencies.smoltcp]
git = "https://github.com/gfreezy/smoltcp"
rev = "10eff99"

default-features = false
features = [
	"std", "log",
	"proto-ipv4",
	"socket-udp",
	"socket-tcp",
	"phy-raw_socket",
]
