[workspace]
members = ["seeker", "dnsserver", "ssclient", "sysconfig", "tun", "config", "crypto", "hermes/hermesdns", "socks5_client"]

[profile.release]
lto = false
#codegen-units = 1
#incremental = false
#opt-level = "z"
#debug = true
