[package]
name = "seeker"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.59"
#runtime = "0.3.0-alpha.6"
futures-preview = "0.3.0-alpha.17"
romio = "0.3.0-alpha.9"
#tokio = "0.1.22"
mio = "0.6.19"
log = "0.4.7"
managed = "0.7.1"
env_logger = "0.6.2"
better-panic = "0.1.2"
#shadowsocks-rust = {version = "1.7.0", features = ["sodium"], default-features = false}

[dependencies.smoltcp]
git = "https://github.com/gfreezy/smoltcp"
branch = "pub-fun"
default-features = false
features = [
	"std", "log",
	"proto-ipv4",
	"socket-udp",
	"socket-tcp",
	"phy-raw_socket",
]
