[package]
name = "dnsserver"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.6.0"
hermesdns = { path = "../hermes/hermesdns" }
config = { path = "../config" }
sled = "0.31.0"
async-trait = "0.1.31"
tracing = "0.1.14"

[dev-dependencies]
tempfile = "3.1.0"
