[package]
name = "config"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shadowsocks-rust = {version = "1.7.0", features = ["sodium"], default-features = false}
serde = { version = "1.0.99", features = ["derive"] }
serde_yaml = "0.8.9"
