[package]
name = "config"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.99", features = ["derive", "rc"] }
serde_yaml = "0.8.9"
bytes = "0.5.4"
tracing = "0.1"
crypto = { path = "../crypto" }
byteorder = "1.3.2"
socks5_client = { path = "../socks5_client" }

[dependencies.smoltcp]
git = "https://github.com/gfreezy/smoltcp"
rev = "ef17f0b"
default-features = false
features = [
	"std", "log",
	"proto-ipv4",
	"socket-udp",
	"socket-tcp",
	"phy-raw_socket",
]
