[package]
name = "ssclient"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["std-future"], default-features = false }
libc = "0.2.62"
bytes = "0.5.4"
byteorder = "1.3.2"
managed = "0.7.1"
mio = "0.6.19"
parking_lot = "0.9.0"
hermesdns = { path = "../hermes/hermesdns" }
sysconfig = { path = "../sysconfig" }
tun = { path = "../tun" }
config = { path = "../config" }
crypto = { path = "../crypto" }
async-trait = "0.1.14"
chrono = "0.4.10"
lazy_static = "1.4.0"
async-std = { git = "https://github.com/gfreezy/async-std", rev = "fb8866c"  }

[dependencies.smoltcp]
git = "https://github.com/gfreezy/smoltcp"
rev = "ef17f0b"
default-features = false
features = [
	"std", "log",
	"proto-ipv4",
	"socket-udp",
	"socket-tcp",
	"phy-raw_socket",
]
