[package]
name = "ssclient"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-futures = { version = "0.2", features = ["std-future"], default-features = false }
bytes = "0.5.4"
byteorder = "1.3.2"
config = { path = "../config" }
crypto = { path = "../crypto" }
async-std = "1.5"
futures = "0.3.4"

[dev-dependencies]
tracing-subscriber = "0.2"
