[package]
name = "crypto"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.5.4"
rand = "0.7.2"
md-5 = "0.8.0"
digest = "0.8.1"
typenum = "1.11.2"
byte_string = "1.0.0"
byteorder = "1"
openssl = { version = "0.10", optional = true }
libc = "0.2.62"
hkdf = "0.8"
hmac = "0.7"
sha-1 = "0.8"
libsodium-sys = { version = "0.2", optional = true }
ring = { version = "0.16", optional = true }

[features]
default = ["sodium", "rc4", "aes-cfb", "aes-ctr", "camellia-cfb", "use-ring"]
sodium = ["libsodium-sys"]
rc4 = ["openssl"]
aes-cfb = ["openssl"]
aes-ctr = ["openssl"]
camellia-cfb = ["openssl"]
use-ring = ["ring"]
