[package]
name = "crypto"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ring = "0.14"
bytes = "0.4.12"
rand = "0.7.2"
md-5 = "0.8.0"
digest = "0.8.1"
typenum = "1.11.2"
byte_string = "1.0.0"
tracing = "0.1"
byteorder = "1"
