[package]
name = "seeker"
version = "0.2.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1.14"
tracing-subscriber = "0.2.5"
tracing-futures = { version = "0.2.4", features = ["std-future"], default-features = false }
config = { path = "../config" }
dnsserver = { path = "../dnsserver" }
ssclient = { path = "../ssclient" }
socks5_client = { path = "../socks5_client" }
http_proxy_client = { path = "../http_proxy_client" }
sysconfig = { path = "../sysconfig" }
tun_nat = { path = "../tun_nat" }
file-rotate = { git = "https://github.com/gfreezy/file-rotate", rev = "0fc0f02" }
async-std = "~1.5.0"
parking_lot = { version = "0.10.2", features = ["deadlock_detection"] }
async-signals = "0.3.1"
libc = "0.2.71"
futures-util = "0.3.5"
clap = "2.33.1"
async-std-resolver = "0.19.5"
ureq = "1.1.1"
crypto = { path = "../crypto" }
bytes = "0.5.4"
base64 = "0.12.1"
anyhow = "1.0.31"
