[package]
name = "seeker"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-core = "0.1"
tracing-subscriber = "0.1"
config = { path = "../config" }
dnsserver = { path = "../dnsserver" }
ssclient = { path = "../ssclient" }
sysconfig = { path = "../sysconfig" }
tun = { path = "../tun" }
async-std = { git = "https://github.com/gfreezy/async-std", rev = "6d39151"}
futures-preview = "0.3.0-alpha"
signal-hook = "0.1.10"

[dependencies.smoltcp]
git = "https://github.com/gfreezy/smoltcp"
rev = "d64d6b9"
default-features = false
features = [
	"std", "log",
	"proto-ipv4",
	"socket-udp",
	"socket-tcp",
	"phy-raw_socket",
]

[dependencies.clap]
version = "2"
