[package]
name = "seeker"
version = "0.2.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tracing = "0.1"
tracing-core = "0.1"
tracing-subscriber = "0.2.1"
tracing-futures = { version = "0.2", features = ["std-future"], default-features = false }
config = { path = "../config" }
dnsserver = { path = "../dnsserver" }
ssclient = { path = "../ssclient" }
socks5_client = { path = "../socks5_client" }
sysconfig = { path = "../sysconfig" }
tun_nat = { path = "../tun_nat" }
async-trait = "0.1"
hermesdns = { path = "../hermes/hermesdns" }
chrono = "0.4"
file-rotate = { git = "https://github.com/gfreezy/file-rotate", rev = "d07b66c" }
async-std = "1.5"
smoltcp = "0.6"
parking_lot = "0.10"
async-signals = "0.3.0-alpha.0"
libc = "0.2"

[dependencies.clap]
version = "2"
