[package]
name = "sysconfig"
version = "0.1.0"
authors = ["gfreezy <gfreezy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
failure = "0.1.5"
libproc = { git = "https://github.com/gfreezy/libproc-rs", rev = "bffc2c4" }
tracing = "0.1"
